Repository best-octopus/bo-backend, pull requests merged in 2024-01, with the labels that each got.

#7 feat : signup api
  .DS_Store
  .gitignore
  build.gradle
  src/main/java/com/bestoctopus/dearme/config/JwtSecurityConfig.java
  src/main/java/com/bestoctopus/dearme/config/RedisConfig.java
  src/main/java/com/bestoctopus/dearme/config/SecurityConfig.java
  src/main/java/com/bestoctopus/dearme/controller/EmotionController.java
  src/main/java/com/bestoctopus/dearme/controller/LogInController.java
  src/main/java/com/bestoctopus/dearme/controller/LogOutController.java
  src/main/java/com/bestoctopus/dearme/controller/TestController.java
  src/main/java/com/bestoctopus/dearme/domain/BookInform.java
  src/main/java/com/bestoctopus/dearme/domain/BookReview.java
  src/main/java/com/bestoctopus/dearme/domain/BucketList.java
  src/main/java/com/bestoctopus/dearme/domain/DailyEmo.java
  src/main/java/com/bestoctopus/dearme/domain/Memo.java
  src/main/java/com/bestoctopus/dearme/domain/Tag.java
  src/main/java/com/bestoctopus/dearme/domain/User.java
  src/main/java/com/bestoctopus/dearme/domain/relation/BookReviewTagRelation.java
  src/main/java/com/bestoctopus/dearme/domain/relation/LikeRelation.java
  src/main/java/com/bestoctopus/dearme/domain/relation/MemoTagRelation.java
  src/main/java/com/bestoctopus/dearme/domain/relation/UserTagRelation.java
  src/main/java/com/bestoctopus/dearme/dto/JwtDto.java
  src/main/java/com/bestoctopus/dearme/dto/UserDto.java
  src/main/java/com/bestoctopus/dearme/dto/UserLogInRequestDto.java
  src/main/java/com/bestoctopus/dearme/dto/UserLogInResponseDto.java
  src/main/java/com/bestoctopus/dearme/exception/GlobalExceptionHandler.java
  src/main/java/com/bestoctopus/dearme/exception/JwtInvalidException.java
  src/main/java/com/bestoctopus/dearme/exception/NotFoundUserException.java
  src/main/java/com/bestoctopus/dearme/exception/NotValidateException.java
  src/main/java/com/bestoctopus/dearme/filters/JwtFilter.java
  src/main/java/com/bestoctopus/dearme/repository/UserRepository.java
  src/main/java/com/bestoctopus/dearme/service/LogInService.java
  src/main/java/com/bestoctopus/dearme/service/LogInServiceImpl.java
  src/main/java/com/bestoctopus/dearme/token/JwtAuthenticationProvider.java
  src/main/java/com/bestoctopus/dearme/token/JwtAuthenticationToken.java
  src/main/java/com/bestoctopus/dearme/token/JwtType.java
  src/main/java/com/bestoctopus/dearme/token/Role.java
  src/main/java/com/bestoctopus/dearme/util/JwtIssuer.java
  src/main/java/com/bestoctopus/dearme/util/RedisUtil.java
  src/main/resources/application-redis.properties
  src/main/resources/application.properties
Labels: feat, api, hyunzzi

#13 fix : emotion api
  src/main/java/com/bestoctopus/dearme/controller/EmotionController.java
  src/main/java/com/bestoctopus/dearme/domain/DailyEmo.java
  src/main/java/com/bestoctopus/dearme/dto/DailyEmoDto.java
  src/main/java/com/bestoctopus/dearme/service/DailyEmoService.java
Labels: fix, api, munyeong

#9 fix : bucketlist API
  src/main/java/com/bestoctopus/dearme/controller/BookReviewController.java
  src/main/java/com/bestoctopus/dearme/controller/BucketListController.java
  src/main/java/com/bestoctopus/dearme/domain/BookReview.java
  src/main/java/com/bestoctopus/dearme/domain/BucketList.java
  src/main/java/com/bestoctopus/dearme/domain/DailyEmo.java
  src/main/java/com/bestoctopus/dearme/dto/BookReviewListDto.java
  src/main/java/com/bestoctopus/dearme/dto/BucketListDto.java
  src/main/java/com/bestoctopus/dearme/dto/PutBucketListDto.java
  src/main/java/com/bestoctopus/dearme/repository/BookReviewRepository.java
  src/main/java/com/bestoctopus/dearme/repository/BucketListRepository.java
  src/main/java/com/bestoctopus/dearme/service/BookReviewService.java
  src/main/java/com/bestoctopus/dearme/service/BucketListService.java
  src/test/java/com/bestoctopus/dearme/DearmeApplicationTests.java
Labels: fix, api, munyeong

#25 fix : bucketlist & emotion api
  src/main/java/com/bestoctopus/dearme/controller/BucketListController.java
  src/main/java/com/bestoctopus/dearme/controller/EmotionController.java
  src/main/java/com/bestoctopus/dearme/domain/BucketList.java
  src/main/java/com/bestoctopus/dearme/dto/BucketListDto.java
  src/main/java/com/bestoctopus/dearme/dto/DailyEmoDto.java
  src/main/java/com/bestoctopus/dearme/dto/ResultDto.java
  src/main/java/com/bestoctopus/dearme/repository/BucketListRepository.java
  src/main/java/com/bestoctopus/dearme/repository/DailyEmoRepository.java
  src/main/java/com/bestoctopus/dearme/service/BucketListService.java
  src/main/java/com/bestoctopus/dearme/service/DailyEmoService.java
Labels: feat, fix, api, munyeong
